# Generated by Django 5.2.8 on 2025-12-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_tag_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(default='custom', max_length=50)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('base_params', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Keyword Provider',
                'verbose_name_plural': 'Keyword Providers',
            },
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('normalized', models.CharField(db_index=True, max_length=128)),
                ('score', models.FloatField(default=0.0)),
                ('locale', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TagsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_public_suggestions', models.BooleanField(default=True, help_text='Allow authenticated users to suggest new tags.')),
                ('enable_ai_suggestions', models.BooleanField(default=True, help_text='Enable AI-assisted tag suggestions where available.')),
                ('show_tag_usage', models.BooleanField(default=True, help_text='Expose tag usage counts in public views.')),
            ],
            options={
                'verbose_name': 'Tags Settings',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='ai_score',
            field=models.FloatField(default=0.0, help_text='Confidence when AI suggested this tag.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='Last content hash used for AI suggestions.', max_length=64),
        ),
        migrations.AddField(
            model_name='tag',
            name='importance',
            field=models.IntegerField(default=0, help_text='Boost for curated/priority tags.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_curated',
            field=models.BooleanField(default=False, help_text='True if reviewed/approved by staff.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='merge_into',
            field=models.ForeignKey(blank=True, help_text='Soft-merge: redirects this tag to another canonical tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent for hierarchical taxonomies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='path_cache',
            field=models.CharField(blank=True, default='', help_text='Cached materialized path for fast tree queries.', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Recent AI suggestions with scores/rationales.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='synonyms_text',
            field=models.TextField(blank=True, default='', help_text='Editable comma-separated synonyms.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Explain when to use this tag.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Use concise, reusable names.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='synonyms',
            field=models.JSONField(blank=True, default=list, help_text='Comma-separated alternatives users might search.'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['normalized_name'], name='tag_normalized_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tag_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'importance', '-usage_count'], name='tag_active_importance_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['merge_into'], name='tag_merge_into_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent'], name='tag_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['path_cache'], name='tag_path_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('merge_into__isnull', True)), fields=('normalized_name',), name='tag_unique_normalized'),
        ),
        migrations.AddField(
            model_name='keywordsuggestion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tags.keywordprovider'),
        ),
        migrations.AddIndex(
            model_name='keywordsuggestion',
            index=models.Index(fields=['normalized'], name='tags_keywor_normali_79f9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordsuggestion',
            index=models.Index(fields=['locale', 'category'], name='tags_keywor_locale_c6b8ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordsuggestion',
            unique_together={('provider', 'normalized')},
        ),
    ]
