# Generated by Django 5.2.8 on 2025-12-10 06:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_keywordprovider_keywordsuggestion_tagssettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=64, unique=True)),
                ('redirect_count', models.PositiveIntegerField(default=0)),
                ('canonical_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='tags.tag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tag Aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='TagAnalytics',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='tags.tag')),
                ('total_usage', models.PositiveIntegerField(default=0)),
                ('unique_authors', models.PositiveIntegerField(default=0)),
                ('avg_engagement', models.FloatField(default=0.0, help_text='Average engagement of tagged content')),
                ('first_used', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('peak_usage_date', models.DateField(blank=True, null=True)),
                ('peak_usage_count', models.PositiveIntegerField(default=0)),
                ('growth_rate_7d', models.FloatField(default=0.0)),
                ('growth_rate_30d', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0, help_text='Content quality score for this tag')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tag Analytics',
                'indexes': [models.Index(fields=['-total_usage'], name='tags_tagana_total_u_0d010d_idx'), models.Index(fields=['-avg_engagement'], name='tags_tagana_avg_eng_8f2b4e_idx'), models.Index(fields=['-quality_score'], name='tags_tagana_quality_2494f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TagBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(help_text='Exact match or regex pattern', max_length=100, unique=True)),
                ('is_regex', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pattern'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class or emoji', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tag Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tags.tagcollection')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('collection', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='tagcollection',
            name='tags',
            field=models.ManyToManyField(related_name='in_collections', through='tags.TagCollectionItem', to='tags.tag'),
        ),
        migrations.CreateModel(
            name='TagMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_tag_name', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('items_migrated', models.PositiveIntegerField(default=0)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_history', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tagcollection',
            unique_together={('owner', 'slug')},
        ),
        migrations.CreateModel(
            name='TagRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('synonym', 'Synonym'), ('related', 'Related'), ('broader', 'Broader Topic'), ('narrower', 'Narrower Topic'), ('replaces', 'Replaces'), ('equivalent', 'Equivalent')], max_length=20)),
                ('strength', models.FloatField(default=1.0, help_text='Relationship strength (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('auto_generated', models.BooleanField(default=False, help_text='Generated by AI/algorithm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='tags.tag')),
                ('to_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='tags.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['from_tag', 'relationship_type'], name='tags_tagrel_from_ta_a41bfb_idx'), models.Index(fields=['to_tag', 'relationship_type'], name='tags_tagrel_to_tag__8bcb9c_idx')],
                'unique_together': {('from_tag', 'to_tag', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='TagSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never (Bookmark Only)')], default='instant', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='tags_tagsub_user_id_d8de46_idx'), models.Index(fields=['tag', 'notification_frequency'], name='tags_tagsub_tag_id_3e95c0_idx')],
                'unique_together': {('tag', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_name', models.CharField(max_length=64)),
                ('normalized_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('merged', 'Merged with Existing')], default='pending', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_suggestion', to='tags.tag')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tag_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tags_tagsug_status_d8baef_idx'), models.Index(fields=['suggested_by', 'status'], name='tags_tagsug_suggest_0ca550_idx')],
            },
        ),
        migrations.CreateModel(
            name='TagTrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Last Hour'), ('daily', 'Last 24 Hours'), ('weekly', 'Last 7 Days'), ('monthly', 'Last 30 Days')], max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0, help_text='Percentage growth vs previous period')),
                ('trending_score', models.FloatField(default=0.0, help_text='Composite trending score')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_data', to='tags.tag')),
            ],
            options={
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'rank'], name='tags_tagtre_period_fce0c6_idx'), models.Index(fields=['period', '-trending_score'], name='tags_tagtre_period_45dc16_idx')],
                'unique_together': {('tag', 'period')},
            },
        ),
    ]
