# Generated by Django 5.2.9 on 2025-12-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0007_remove_taganalytics_tag_remove_tagblacklist_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, help_text='The ID of the specific object being tagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='The model class being tagged', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who applied this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(help_text='The tag being applied', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Tagged Item',
                'verbose_name_plural': 'Tagged Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tags_tagged_content_eaa81e_idx'), models.Index(fields=['tag', 'content_type'], name='tags_tagged_tag_id_eb7179_idx'), models.Index(fields=['created_at'], name='tags_tagged_created_90a048_idx')],
                'unique_together': {('tag', 'content_type', 'object_id')},
            },
        ),
    ]
