# Generated by Django 5.2.8 on 2025-12-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i18n', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appmanifest',
            new_name='i18n_appman_app_id_d95a76_idx',
            old_name='i18n_manifest_app_idx',
        ),
        migrations.RenameIndex(
            model_name='languageprofile',
            new_name='i18n_langua_app_id_e6cdef_idx',
            old_name='i18n_lang_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='missingkeylog',
            new_name='i18n_missin_app_id_0684f5_idx',
            old_name='i18n_missing_app_locale_idx',
        ),
        migrations.RenameIndex(
            model_name='missingkeylog',
            new_name='i18n_missin_created_119360_idx',
            old_name='i18n_missing_created_idx',
        ),
        migrations.RenameIndex(
            model_name='theme',
            new_name='i18n_theme_app_id_1b09b3_idx',
            old_name='i18n_theme_app_site_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='themeassignment',
            new_name='i18n_themea_app_id_1026ec_idx',
            old_name='i18n_theme_assignment_idx',
        ),
        migrations.RenameIndex(
            model_name='translationkey',
            new_name='i18n_transl_app_id_fd4f36_idx',
            old_name='i18n_tkey_idx',
        ),
        migrations.RenameIndex(
            model_name='translationvalue',
            new_name='i18n_transl_locale_ec6ae3_idx',
            old_name='i18n_tvalue_locale_status_idx',
        ),
    ]
