# Generated by Django 5.2.8 on 2025-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
