# Generated by Django 5.2.8 on 2025-12-05 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('basic_fingerprinting', models.BooleanField(default=True)),
                ('enhanced_fingerprinting', models.BooleanField(default=False)),
                ('device_locking_mode', models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('strict', 'Strict')], default='none', max_length=20)),
                ('mfa_requirement', models.CharField(choices=[('none', 'None'), ('new_device', 'New Device'), ('always', 'Always')], default='none', max_length=20)),
                ('ai_risk_scoring', models.BooleanField(default=False)),
                ('service_level_rules', models.JSONField(blank=True, default=dict)),
                ('monthly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per month for this app (None = use global).', null=True)),
                ('yearly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per calendar year for this app (None = use global).', null=True)),
                ('ad_unlock_enabled', models.BooleanField(default=False, help_text='Allow ad-based unlocks for device quota in this app.')),
            ],
            options={
                'verbose_name': 'App Policy',
                'verbose_name_plural': 'App Policies',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_fingerprinting_enabled', models.BooleanField(default=True)),
                ('enhanced_fingerprinting_enabled', models.BooleanField(default=False)),
                ('enterprise_device_management_enabled', models.BooleanField(default=False)),
                ('max_devices_default', models.PositiveIntegerField(default=5)),
                ('monthly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per month (None = unlimited).', null=True)),
                ('yearly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per calendar year (None = unlimited).', null=True)),
                ('ad_unlock_enabled', models.BooleanField(default=False, help_text='Allow users to unlock device quota by completing rewarded ads.')),
                ('strict_new_device_login', models.BooleanField(default=False)),
                ('require_mfa_on_new_device', models.BooleanField(default=False)),
                ('device_expiry_days', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_server_fallback', models.BooleanField(default=True)),
                ('ai_risk_scoring_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Device Config',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_uuid', models.CharField(max_length=128)),
                ('fingerprint_hash', models.CharField(blank=True, default='', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('browser_family', models.CharField(blank=True, default='', max_length=50)),
                ('os_family', models.CharField(blank=True, default='', max_length=50)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('max_privilege_level', models.CharField(choices=[('normal', 'Normal'), ('restricted', 'Restricted'), ('blocked', 'Blocked')], default='normal', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('download_attempt', 'Download Attempt'), ('policy_violation', 'Policy Violation'), ('registration', 'Registration'), ('device_trusted', 'Device Trusted'), ('device_blocked', 'Device Blocked'), ('mfa_challenge', 'MFA Challenge'), ('mfa_failed', 'MFA Failed'), ('mfa_passed', 'MFA Passed'), ('service_access', 'Service Access')], max_length=50)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('geo_region', models.CharField(blank=True, default='', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'machine_uuid'], name='device_user_machine_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_blocked'], name='device_blocked_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen_at'], name='device_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['risk_score'], name='device_risk_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'machine_uuid'), name='device_user_machine_uuid_unique'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['user'], name='device_event_user_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device'], name='device_event_device_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type'], name='device_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['created_at'], name='device_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['success'], name='device_event_success_idx'),
        ),
    ]
