# Generated by Django 5.2.8 on 2025-12-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_userdevicequota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeviceQuota',
        ),
    ]
