# Generated by Django 5.2.8 on 2025-12-07 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_delete_userdevicequota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op: quota model already created in 0004; retained for graph continuity
    ]
