# Generated by Django 5.2.8 on 2025-12-09 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_hardware_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='device_user_machine_uuid_unique',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='device_user_machine_idx',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware_uuid',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'hardware_uuid'), name='device_user_hardware_uuid_unique'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='machine_uuid',
        ),
    ]
