# Generated by Django 5.2.8 on 2025-12-09 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_os_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='device_user_hardware_uuid_unique',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='device_user_hardware_idx',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_key_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('ES256', 'ES256'), ('Ed25519', 'Ed25519')], default='ES256', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'os_fingerprint'), name='device_user_os_fingerprint_unique'),
        ),
    ]
