# Generated by Django 5.2.9 on 2025-12-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_dedupe_os_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_trusted',
            field=models.BooleanField(default=True),
        ),
    ]
