# Generated by Django 6.0 on 2025-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_enabled', models.BooleanField(default=True, help_text='Turn SEO module on/off (meta tags, schema, link tools).')),
                ('ads_enabled', models.BooleanField(default=True, help_text='Turn Ads module on/off (slots, rotation, tracking).')),
                ('tags_enabled', models.BooleanField(default=True, help_text='Turn Tags module on/off (taxonomy, tag pages, tag APIs).')),
                ('blog_enabled', models.BooleanField(default=True, help_text='Turn Blog module on/off (posts, feeds, public views).')),
                ('comments_enabled', models.BooleanField(default=True, help_text='Turn Comments module on/off (API + moderation UI).')),
                ('distribution_enabled', models.BooleanField(default=True, help_text='Turn Distribution module on/off (syndication/sharing).')),
                ('users_enabled', models.BooleanField(default=True, help_text='Turn Users module on/off (auth, profile, notifications).')),
                ('device_identity_enabled', models.BooleanField(default=True, help_text='Turn Device Identity on/off (fingerprint/login policy).')),
                ('crawler_guard_enabled', models.BooleanField(default=True, help_text='Turn Crawler Guard on/off (anti-scraping middleware).')),
                ('ai_behavior_enabled', models.BooleanField(default=True, help_text='Turn AI Behavior Engine on/off (risk insights).')),
                ('i18n_themes_enabled', models.BooleanField(default=True, help_text='Turn i18n + Themes on/off (runtime tokens + translations).')),
                ('ai_enabled', models.BooleanField(default=True, help_text='Turn AI Platform on/off (models, workflows, knowledge).')),
            ],
            options={
                'verbose_name': 'App Registry',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('value', models.FloatField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='core_metric_name_a0bb32_idx')],
            },
        ),
    ]
