# Generated by Django 5.2.8 on 2025-11-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postdraft_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdraft',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='postrevision',
            options={'ordering': ['-created_at']},
        ),
    ]
