# Generated by Django 5.2.8 on 2025-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postdraft_options_alter_postrevision_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_blog', models.BooleanField(default=True)),
                ('enable_blog_comments', models.BooleanField(default=True)),
                ('allow_user_blog_posts', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Settings',
            },
        ),
    ]
