# Generated by Django 5.2.8 on 2025-12-05

from django.db import migrations, models
import django.core.validators
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="HTML produced by the WYSIWYG editor; validated and sanitized upstream.",
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(50000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short abstract shown in lists; capped to ~1000 characters.",
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="3-200 characters.",
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(200),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "publish_at"], name="blog_post_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "status"], name="blog_post_author_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                django.db.models.functions.text.Lower("slug"),
                name="blog_post_slug_ci_idx",
            ),
        ),
    ]
