# Generated by Django 5.2.8 on 2025-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_parent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_parent_name_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='noindex',
            field=models.BooleanField(default=False, help_text='If true, exclude from indexing until manually cleared.'),
        ),
    ]
