# Generated by Django 5.2.8 on 2025-12-07 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='summary',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
