# Generated by Django 5.2.8 on 2025-12-05

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_commentsettings_comment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                help_text="Plain text or sanitized HTML from editor; capped to 5k chars.",
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(5000),
                ],
            ),
        ),
    ]
