# Generated by Django 5.2.8 on 2025-12-10 06:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_body_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnalytics',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='comments.comment')),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('net_votes', models.IntegerField(default=0)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('award_count', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Calculated engagement metric')),
                ('quality_score', models.FloatField(default=0.0, help_text='AI-calculated quality score')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-engagement_score'], name='comments_co_engagem_267bb9_idx'), models.Index(fields=['-quality_score'], name='comments_co_quality_5c9ec6_idx'), models.Index(fields=['-net_votes'], name='comments_co_net_vot_7b485e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_type', models.CharField(choices=[('gold', '🥇 Gold'), ('silver', '🥈 Silver'), ('bronze', '🥉 Bronze'), ('helpful', '✨ Helpful'), ('insightful', '💎 Insightful'), ('expert', '👨\u200d🎓 Expert'), ('popular', '🔥 Popular'), ('trending', '📈 Trending')], max_length=20)),
                ('auto_assigned', models.BooleanField(default=False, help_text='Auto-assigned by system based on metrics')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='comments.comment')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', 'award_type'], name='comments_co_comment_238c69_idx'), models.Index(fields=['given_by', '-created_at'], name='comments_co_given_b_dd1045_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Personal notes about this bookmark')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='comments_co_user_id_dae597_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_body', models.TextField()),
                ('edit_reason', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='comments.comment')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', '-created_at'], name='comments_co_comment_2429c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('off_topic', 'Off Topic'), ('misinformation', 'Misinformation'), ('nsfw', 'NSFW Content'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='comments.comment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'resolved'], name='comments_co_comment_0df701_idx'), models.Index(fields=['reason', 'resolved'], name='comments_co_reason_e338e1_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='comments.comment')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mentioned_user', 'notified'], name='comments_co_mention_ff3307_idx')],
                'unique_together': {('comment', 'mentioned_user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('insightful', '💡 Insightful'), ('funny', '😂 Funny'), ('celebrate', '🎉 Celebrate'), ('support', '🙌 Support'), ('curious', '🤔 Curious'), ('disagree', '👎 Disagree')], default='like', max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'reaction_type'], name='comments_co_comment_b1b5f4_idx'), models.Index(fields=['user', '-created_at'], name='comments_co_user_id_721795_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_replies', models.PositiveIntegerField(default=0)),
                ('max_depth', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_count', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('root_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_metadata', to='comments.comment')),
            ],
            options={
                'indexes': [models.Index(fields=['-last_activity'], name='comments_co_last_ac_46f332_idx'), models.Index(fields=['is_featured', '-last_activity'], name='comments_co_is_feat_41f3b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'vote'], name='comments_co_comment_82b0c9_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('delete', 'Deleted'), ('edit', 'Edited'), ('lock', 'Locked'), ('unlock', 'Unlocked'), ('warn_user', 'Warned User'), ('ban_user', 'Banned User'), ('unban_user', 'Unbanned User'), ('mark_spam', 'Marked as Spam')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('auto_moderated', models.BooleanField(default=False, help_text='Action taken by AI/automation')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='comments.comment')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', '-created_at'], name='comments_mo_comment_5485c7_idx'), models.Index(fields=['moderator', '-created_at'], name='comments_mo_moderat_c7b394_idx'), models.Index(fields=['action', '-created_at'], name='comments_mo_action_a7ca4e_idx')],
            },
        ),
    ]
