# Generated by Django 5.2.8 on 2025-11-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicefingerprint',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='devicefingerprint',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint_hash'), name='unique_user_fingerprint'),
        ),
    ]
