# Generated by Django 5.2.8 on 2025-11-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manual_signup',
            field=models.BooleanField(default=False),
        ),
    ]
