# Generated by Django 5.2.8 on 2025-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_verification_code_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_signup', models.BooleanField(default=True)),
                ('enable_password_reset', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=False)),
                ('mfa_totp_issuer', models.CharField(default='Site', max_length=50)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=300)),
                ('enable_payments', models.BooleanField(default=True)),
                ('required_profile_fields', models.JSONField(blank=True, default=list, help_text='List of user model fields that should trigger a profile-completion prompt.')),
            ],
            options={
                'verbose_name': 'Users Settings',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code_sent_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Referral system disabled by default; code is optional.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'Author'), ('moderator', 'Moderator'), ('reader', 'Reader')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DeviceFingerprint',
        ),
    ]
