# Generated by Django 5.2.8 on 2025-12-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
