# Generated by Django 5.0.6 on 2025-12-10 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_bio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('reaction', 'Reaction'), ('mention', 'Mention'), ('vote', 'Vote'), ('award', 'Award'), ('post', 'Post'), ('like', 'Like'), ('follow', 'Follow'), ('security', 'Security'), ('moderation', 'Moderation'), ('system', 'System')], default='system', help_text='Type of action that triggered notification', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name for UI display (e.g., comment, heart, bell)', max_length=50),
        ),
    ]
