# Generated by Django 5.0.6 on 2025-12-10 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_enhance_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_comments', models.BooleanField(default=True, help_text='Email when someone comments on your posts')),
                ('email_replies', models.BooleanField(default=True, help_text='Email when someone replies to your comments')),
                ('email_mentions', models.BooleanField(default=True, help_text='Email when someone mentions you')),
                ('email_new_posts', models.BooleanField(default=False, help_text='Email about new blog posts')),
                ('email_security', models.BooleanField(default=True, help_text='Email for security alerts (always enabled)')),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=10)),
                ('web_comments', models.BooleanField(default=True, help_text='Web notifications for comment interactions')),
                ('web_awards', models.BooleanField(default=True, help_text='Web notifications for awards and achievements')),
                ('web_moderation', models.BooleanField(default=True, help_text='Web notifications for moderation updates')),
                ('web_system', models.BooleanField(default=True, help_text='Web notifications for system announcements')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable browser push notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Mute notifications during quiet hours')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Start of quiet hours')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='End of quiet hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Encryption key', max_length=255)),
                ('auth', models.CharField(help_text='Authentication secret', max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_user_active_idx')],
            },
        ),
    ]
