# Generated by Django - Manual Migration
# Replaces AppStoreCredentials with SocialPostingAccount for social media auto-posting

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_social_provider_config'),
    ]

    operations = [
        # Remove AppStoreCredentials table
        migrations.DeleteModel(
            name='AppStoreCredentials',
        ),
        
        # Create SocialPostingAccount table
        migrations.CreateModel(
            name='SocialPostingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[
                    ('facebook', 'Facebook (Page/Group)'),
                    ('twitter', 'Twitter / X'),
                    ('linkedin', 'LinkedIn (Company/Personal)'),
                    ('telegram', 'Telegram (Channel/Group)'),
                    ('whatsapp', 'WhatsApp Business'),
                    ('instagram', 'Instagram (via Facebook)'),
                    ('discord', 'Discord (Webhook)'),
                    ('reddit', 'Reddit'),
                    ('pinterest', 'Pinterest'),
                    ('tumblr', 'Tumblr'),
                    ('medium', 'Medium'),
                    ('threads', 'Threads'),
                ], max_length=32)),
                ('account_name', models.CharField(help_text='Account/Page/Channel name', max_length=255)),
                ('auth_type', models.CharField(choices=[
                    ('oauth2', 'OAuth 2.0 (Browser Login)'),
                    ('api_token', 'API Token / Bot Token'),
                    ('webhook', 'Webhook URL'),
                    ('api_key_secret', 'API Key + Secret'),
                    ('access_token', 'Access Token (Long-lived)'),
                ], default='oauth2', max_length=32)),
                
                # Destination details
                ('destination_type', models.CharField(choices=[
                    ('page', 'Page'),
                    ('group', 'Group'),
                    ('channel', 'Channel'),
                    ('profile', 'Personal Profile'),
                    ('company', 'Company Page'),
                    ('subreddit', 'Subreddit'),
                    ('board', 'Board'),
                    ('blog', 'Blog'),
                ], default='page', max_length=32)),
                ('destination_id', models.CharField(blank=True, help_text='Page ID, Channel ID, Group ID, etc.', max_length=255)),
                ('destination_name', models.CharField(blank=True, help_text='Human-readable destination name', max_length=255)),
                ('destination_url', models.URLField(blank=True, help_text='URL to the page/channel/group')),
                
                # Encrypted credentials
                ('_api_key_encrypted', models.BinaryField(blank=True, db_column='api_key_encrypted', null=True)),
                ('_api_secret_encrypted', models.BinaryField(blank=True, db_column='api_secret_encrypted', null=True)),
                ('_access_token_encrypted', models.BinaryField(blank=True, db_column='access_token_encrypted', null=True)),
                ('_refresh_token_encrypted', models.BinaryField(blank=True, db_column='refresh_token_encrypted', null=True)),
                ('_webhook_url_encrypted', models.BinaryField(blank=True, db_column='webhook_url_encrypted', null=True)),
                ('_bot_token_encrypted', models.BinaryField(blank=True, db_column='bot_token_encrypted', null=True)),
                ('_additional_config_encrypted', models.BinaryField(blank=True, db_column='additional_config_encrypted', null=True)),
                
                # Token management
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('token_scope', models.CharField(blank=True, help_text='OAuth scopes granted', max_length=512)),
                
                # Account metadata
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('account_username', models.CharField(blank=True, max_length=255)),
                ('account_avatar_url', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                
                # Status
                ('status', models.CharField(choices=[
                    ('unconfigured', 'Not Configured'),
                    ('pending_oauth', 'Pending OAuth Authorization'),
                    ('active', 'Active'),
                    ('token_expired', 'Token Expired - Re-auth Required'),
                    ('error', 'Configuration Error'),
                    ('disabled', 'Disabled'),
                ], default='unconfigured', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                
                # Auto-posting configuration
                ('auto_post_enabled', models.BooleanField(default=True, help_text='Auto-post new content')),
                ('post_content_types', models.CharField(choices=[
                    ('blogs', 'Blog Posts'),
                    ('firmwares', 'Firmware Uploads'),
                    ('both', 'Both Blogs & Firmwares'),
                ], default='both', max_length=32)),
                ('post_template', models.TextField(blank=True, help_text='Custom post template with placeholders: {title}, {excerpt}, {url}, {tags}')),
                ('include_image', models.BooleanField(default=True, help_text='Include featured image in posts')),
                ('include_link', models.BooleanField(default=True, help_text='Include link to full content')),
                ('hashtags', models.CharField(blank=True, help_text='Default hashtags to add', max_length=512)),
                
                # Rate limiting
                ('min_post_interval_minutes', models.IntegerField(default=60, help_text='Minimum minutes between posts')),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('posts_today', models.IntegerField(default=0)),
                ('daily_post_limit', models.IntegerField(default=10, help_text='Maximum posts per day')),
                
                # Stats
                ('total_posts', models.IntegerField(default=0)),
                ('successful_posts', models.IntegerField(default=0)),
                ('failed_posts', models.IntegerField(default=0)),
                
                # Error tracking
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.IntegerField(default=0)),
                
                # Notes
                ('notes', models.TextField(blank=True, default='')),
                
                # Timestamps
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='created_social_posting_accounts', 
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Social Posting Account',
                'verbose_name_plural': 'Social Posting Accounts',
                'ordering': ['platform', 'account_name'],
            },
        ),
    ]
