# Generated by Django 5.2.9 on 2025-12-23 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_referral_fields_if_exist(apps, schema_editor):
    """Remove referral fields only if they exist in the database."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if columns exist before trying to remove them
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'users_customuser' AND column_name IN ('referral_code', 'referred_by_id')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]

        if 'referral_code' in existing_columns:
            cursor.execute('ALTER TABLE users_customuser DROP COLUMN IF EXISTS referral_code')
        if 'referred_by_id' in existing_columns:
            cursor.execute('ALTER TABLE users_customuser DROP COLUMN IF EXISTS referred_by_id')

        # Try to drop the index if it exists
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'users_customuser' AND indexname = 'user_referral_idx'
        """)
        if cursor.fetchone():
            cursor.execute('DROP INDEX IF EXISTS user_referral_idx')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_replace_appstore_with_socialposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('totp', 'TOTP Authenticator App'), ('backup', 'Backup Codes')], default='totp', max_length=16)),
                ('name', models.CharField(default='Authenticator App', max_length=64)),
                ('secret_encrypted', models.CharField(blank=True, default='', max_length=512)),
                ('backup_codes_hash', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary MFA device')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
            },
        ),
        # Use RunPython to conditionally remove fields that may not exist
        migrations.RunPython(remove_referral_fields_if_exist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='can_create_blog_posts',
            field=models.BooleanField(default=False, help_text='Allow this user to create blog posts (individual permission override)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code (auto-detected from IP)', max_length=2),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mfadevice',
            index=models.Index(fields=['user', 'is_active'], name='mfa_user_active_idx'),
        ),
    ]
