# Generated by Django 5.2.9 on 2025-12-23 15:54

from django.db import migrations


def cleanup_referral_if_exists(apps, schema_editor):
    """
    Safely remove referral columns and index only if they exist.
    Migration 0016 may have already removed them via RunPython.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        # Check existing columns
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'users_customuser' AND column_name IN ('referral_code', 'referred_by_id')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Drop columns if they exist
        if 'referral_code' in existing_columns:
            cursor.execute('ALTER TABLE users_customuser DROP COLUMN referral_code')
        if 'referred_by_id' in existing_columns:
            cursor.execute('ALTER TABLE users_customuser DROP COLUMN referred_by_id')
        
        # Drop index if exists
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'users_customuser' AND indexname = 'user_referral_idx'
        """)
        if cursor.fetchone():
            cursor.execute('DROP INDEX user_referral_idx')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_mfadevice_remove_customuser_user_referral_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_referral_if_exists, migrations.RunPython.noop),
    ]
