# Generated by Django 5.2.8 on 2025-11-28 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, unique=True)),
                ('target', models.CharField(max_length=255)),
                ('is_permanent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('lastmod', models.DateTimeField(blank=True, null=True)),
                ('changefreq', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('keywords', models.TextField(blank=True, default='')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='LinkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('is_applied', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_from', to='seo.linkableentity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_to', to='seo.linkableentity')),
            ],
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('locked', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='seo.seomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=320)),
                ('keywords', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('og_image', models.URLField(blank=True, default='')),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='seo.seomodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='linkableentity',
            index=models.Index(fields=['content_type', 'object_id'], name='seo_linkabl_content_2a6c07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkableentity',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='linksuggestion',
            unique_together={('source', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='seomodel',
            unique_together={('content_type', 'object_id')},
        ),
    ]
