# Generated by Django 5.2.8 on 2025-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
