# Generated by Django 5.2.8 on 2025-11-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_metadata_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metadata',
            name='focus_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metadata',
            name='robots_directives',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='social_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='metadata',
            name='social_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitemapentry',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemapentry',
            name='last_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
