# Generated by Django 5.2.8 on 2025-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_seomodel_created_by_alter_seomodel_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_enabled', models.BooleanField(default=True)),
                ('auto_meta_enabled', models.BooleanField(default=False)),
                ('auto_schema_enabled', models.BooleanField(default=False)),
                ('auto_linking_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SEO Settings',
            },
        ),
    ]
