# Generated by Django 5.2.8 on 2025-11-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='template_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
