# Generated by Django 5.2.8 on 2025-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_adcreative_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_enabled', models.BooleanField(default=False)),
                ('affiliate_enabled', models.BooleanField(default=False)),
                ('ad_networks_enabled', models.BooleanField(default=False)),
                ('ad_aggressiveness_level', models.CharField(choices=[('minimal', 'Minimal'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
            ],
            options={
                'verbose_name': 'Ads Settings',
            },
        ),
        migrations.AddField(
            model_name='adevent',
            name='consent_granted',
            field=models.BooleanField(default=False, help_text='True if user consented to ads tracking.'),
        ),
    ]
