# Generated by Django 5.2.8 on 2025-12-07 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0011_alter_posttranslation_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_enabled', models.BooleanField(default=True)),
                ('auto_fanout_on_publish', models.BooleanField(default=True, help_text='Automatically queue distribution when a post is published.')),
                ('default_channels', models.JSONField(blank=True, default=list, help_text='Optional override for enabled channels (empty = all supported).')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts per job before marking as failed.')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=1800, help_text='Minimum age (seconds) before retrying a failed job.')),
                ('allow_indexing_jobs', models.BooleanField(default=False, help_text='Allow search engine indexing submit jobs (Google/Bing).')),
            ],
            options={
                'verbose_name': 'Distribution Settings',
            },
        ),
        migrations.CreateModel(
            name='SyndicationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('endpoint', models.URLField()),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('token', 'Token'), ('basic', 'Basic'), ('api_key', 'API Key')], default='none', max_length=32)),
                ('format', models.CharField(choices=[('rss', 'RSS'), ('json', 'JSON Feed'), ('api', 'Custom API'), ('graphql', 'GraphQL')], default='rss', max_length=32)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShareJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('external_post_id', models.CharField(blank=True, default='', max_length=200)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_jobs', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('response_code', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='distribution.sharejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channel identifiers')),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_plans', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_plans', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sharejob',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='distribution.shareplan'),
        ),
        migrations.CreateModel(
            name='ShareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('body_template', models.TextField(help_text='Use placeholders: {title}, {url}, {summary}, {hashtags}')),
                ('media_template', models.TextField(blank=True, default='')),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel', 'name'],
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'account_name'],
                'unique_together': {('channel', 'account_name')},
            },
        ),
        migrations.AddField(
            model_name='sharejob',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='distribution.socialaccount'),
        ),
        migrations.CreateModel(
            name='WebSubSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_url', models.URLField()),
                ('hub_url', models.URLField()),
                ('secret', models.CharField(blank=True, default='', max_length=200)),
                ('lease_seconds', models.PositiveIntegerField(default=864000)),
                ('active', models.BooleanField(default=True)),
                ('last_challenge_at', models.DateTimeField(blank=True, null=True)),
                ('last_pinged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('topic_url', 'hub_url')},
            },
        ),
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('variant_type', models.CharField(choices=[('summary', 'Summary'), ('caption', 'Caption'), ('tags', 'Hashtags/Tags'), ('image_prompt', 'Image prompt'), ('thread', 'Thread/long-form'), ('email', 'Email')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_variants', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='blog.post')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('post', 'channel', 'variant_type')},
            },
        ),
        migrations.AddIndex(
            model_name='sharejob',
            index=models.Index(fields=['channel', 'status'], name='distributio_channel_b266e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sharejob',
            index=models.Index(fields=['schedule_at'], name='distributio_schedul_00fc93_idx'),
        ),
    ]
