# Generated by Django 5.2.9 on 2025-12-20 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('distribution', '0003_distributionsettings_require_admin_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('content_url', models.URLField(blank=True, default='')),
                ('target_channels', models.JSONField(blank=True, default=list, help_text='List of channels to distribute to (twitter, linkedin, facebook, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('distributing', 'Distributing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('max_seo_tags', models.PositiveIntegerField(default=10, help_text='Maximum number of SEO tags to avoid over-optimization')),
                ('max_auto_tags', models.PositiveIntegerField(default=15, help_text='Maximum number of auto-generated tags')),
                ('max_platforms', models.PositiveIntegerField(default=5, help_text='Maximum number of platforms to distribute to simultaneously')),
                ('priority', models.PositiveIntegerField(default=5, help_text='1=highest, 10=lowest')),
                ('schedule_at', models.DateTimeField(blank=True, help_text='Schedule distribution for later', null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_count', models.PositiveIntegerField(default=0, help_text='Number of successful distributions')),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional distribution metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Distribution',
                'verbose_name_plural': 'Content Distributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='distributio_content_a873d0_idx'), models.Index(fields=['status', 'schedule_at'], name='distributio_status_c2ca8b_idx'), models.Index(fields=['priority', 'created_at'], name='distributio_priorit_a988b7_idx')],
            },
        ),
    ]
