# Generated by Django 5.2.9 on 2025-12-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_contentdistribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionsettings',
            options={'verbose_name': 'Distribution Settings', 'verbose_name_plural': 'Distribution Settings'},
        ),
        migrations.RemoveField(
            model_name='contentdistribution',
            name='max_auto_tags',
        ),
        migrations.RemoveField(
            model_name='contentdistribution',
            name='max_platforms',
        ),
        migrations.RemoveField(
            model_name='contentdistribution',
            name='max_seo_tags',
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='auto_tag_frequency_days',
            field=models.PositiveIntegerField(default=7, help_text='How often (in days) to regenerate auto-tags for existing content. Lower = more frequent updates. 0 = never update.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='distribution_frequency_hours',
            field=models.PositiveIntegerField(default=4, help_text='Minimum hours between auto-distributions for same content. Prevents spam. Recommended: 4-24 hours.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='enable_firmware_auto_distribution',
            field=models.BooleanField(default=True, help_text='Auto-distribute firmware blog posts when created/updated. Disable to distribute firmware posts manually only.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='max_auto_tags',
            field=models.PositiveIntegerField(default=15, help_text='⚠️ Maximum auto-generated tags per post. Over-tagging reduces content quality. Recommended: 10-15. Platform limits apply.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='max_platforms_per_content',
            field=models.PositiveIntegerField(default=5, help_text='⚠️ CRITICAL: Maximum platforms to distribute to simultaneously. Recommended: 5 or less to avoid spam detection. Higher values risk platform bans.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='max_seo_description_length',
            field=models.PositiveIntegerField(default=160, help_text='Maximum characters for meta descriptions. Google displays ~160 chars. Keep it concise for better CTR.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='max_seo_tags',
            field=models.PositiveIntegerField(default=10, help_text='⚠️ Maximum SEO-focused tags per content. Too many tags = keyword stuffing = Google penalty. Recommended: 5-10.'),
        ),
        migrations.AddField(
            model_name='distributionsettings',
            name='max_seo_title_length',
            field=models.PositiveIntegerField(default=60, help_text='Maximum characters for SEO titles. Google displays ~60 chars. Longer titles get truncated in search results.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='allow_indexing_jobs',
            field=models.BooleanField(default=False, help_text='Allow automatic submission to search engines (Google/Bing indexing APIs). Requires API keys. Disable if not configured.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='auto_fanout_on_publish',
            field=models.BooleanField(default=True, help_text='Automatically queue distribution when blog posts are published. Disable for manual control.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='default_channels',
            field=models.JSONField(blank=True, default=list, help_text="Default channels for auto-distribution (empty = use all active channels). Example: ['twitter', 'facebook', 'linkedin']"),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='distribution_enabled',
            field=models.BooleanField(default=True, help_text='Master switch: Enable/disable all content distribution globally.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum retry attempts per failed distribution job before marking as permanently failed.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=False, help_text='Require manual admin approval before executing distribution jobs. Good for auditing but slows automation.'),
        ),
        migrations.AlterField(
            model_name='distributionsettings',
            name='retry_backoff_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Wait time (seconds) before retrying a failed job. 1800s = 30 minutes. Use exponential backoff for rate limits.'),
        ),
    ]
