# Generated by Django 5.2.8 on 2025-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_categories', models.JSONField(blank=True, default=dict)),
                ('policy_version', models.CharField(blank=True, max_length=20)),
                ('site_domain', models.CharField(default='default', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consent log',
                'verbose_name_plural': 'Consent logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('site_domain', models.CharField(db_index=True, default='default', help_text='Domain this policy belongs to.', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories_snapshot', models.JSONField(blank=True, default=dict)),
                ('banner_text', models.TextField(blank=True, default='We use cookies to improve your browsing experience.')),
                ('manage_text', models.TextField(blank=True, default='Manage your cookie preferences.')),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300, help_text='Cache TTL for the active policy payload.')),
            ],
            options={
                'verbose_name': 'Consent policy',
                'verbose_name_plural': 'Consent policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('policy_version', models.CharField(blank=True, db_column='policy_version_str', max_length=20)),
                ('site_domain', models.CharField(default='default', max_length=100)),
                ('accepted_categories', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consent record',
                'verbose_name_plural': 'Consent records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consent category',
                'verbose_name_plural': 'Consent categories',
                'ordering': ['required', 'name'],
                'indexes': [models.Index(fields=['slug'], name='consent_cat_slug_idx')],
            },
        ),
    ]
