# Generated by Django 5.2.8 on 2025-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
