# Generated by Django 5.2.8 on 2025-11-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['site_domain'], name='consent_policy_site_idx'),
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['version'], name='consent_policy_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site_domain', 'is_active'), name='unique_active_policy_per_site'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='policy',
            field=models.ForeignKey(blank=True, db_column='policy_version', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='consent.consentpolicy', to_field='version'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['timestamp'], name='consent_log_time_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['policy_version'], name='consent_rec_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['site_domain'], name='consent_rec_site_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', 'site_domain', 'updated_at'], name='consent_user_site_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('user', 'policy_version', 'site_domain'), name='unique_consent_per_user'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('session_key', 'policy_version', 'site_domain'), name='unique_consent_per_session'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('session_key__isnull', False), models.Q(('session_key', ''), _negated=True)), _connector='OR'), name='valid_user_or_session'),
        ),
    ]
