# Generated by Django 5.2.8 on 2025-11-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_consentpolicy_updated_at_consentrecord_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consent category',
                'verbose_name_plural': 'Consent categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_categories', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consent log',
                'verbose_name_plural': 'Consent logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='consentpolicy',
            options={'verbose_name': 'Consent policy', 'verbose_name_plural': 'Consent policies'},
        ),
        migrations.AlterModelOptions(
            name='consentrecord',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='consentrecord',
            name='consent_con_policy__45a223_idx',
        ),
        migrations.RemoveField(
            model_name='consentpolicy',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='consentpolicy',
            name='text',
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='categories_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='accepted_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='site_domain',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('session_key', 'policy_version', 'site_domain'), name='unique_consent_record'),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
