# Generated by Django 5.2.8 on 2025-12-04 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _drop_legacy_consent_columns(schema_editor):
    """
    Safely drop legacy consent columns on databases that support ALTER TABLE DROP COLUMN.
    SQLite is skipped to avoid table rewrites during dev; extra columns there are harmless.
    """
    vendor = getattr(schema_editor.connection, "vendor", "")
    if vendor == "sqlite":
        return

    statements = [
        ('consent_consentrecord', ('user_id', 'policy_id')),
        ('consent_consentlog', ('user_id',)),
    ]
    with schema_editor.connection.cursor() as cursor:
        for table, columns in statements:
            for col in columns:
                try:
                    cursor.execute(f'ALTER TABLE "{table}" DROP COLUMN IF EXISTS "{col}";')
                except Exception:
                    # Ignore if column or backend does not support IF EXISTS
                    try:
                        cursor.execute(f'ALTER TABLE "{table}" DROP COLUMN "{col}";')
                    except Exception:
                        pass


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(default='accepted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='consentcategory',
            options={'managed': False, 'ordering': ['index', 'slug']},
        ),
        migrations.AlterModelOptions(
            name='consentpolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='consentpolicy',
            name='unique_active_policy_per_site',
        ),
        migrations.RemoveIndex(
            model_name='consentpolicy',
            name='consent_policy_site_idx',
        ),
        migrations.RemoveIndex(
            model_name='consentpolicy',
            name='consent_policy_version_idx',
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consentpolicy',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='banner_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='cache_ttl_seconds',
            field=models.IntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='manage_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='site_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='version',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='consentdecision',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.consentpolicy'),
        ),
        migrations.AddField(
            model_name='consentdecision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='consent.consentdecision'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.consentpolicy'),
        ),
        # Drop legacy user/policy columns on non-SQLite backends; SQLite keeps them to avoid table remakes.
        migrations.RunPython(
            code=lambda apps, schema_editor: _drop_legacy_consent_columns(schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='ConsentLog',
        ),
        migrations.DeleteModel(
            name='ConsentRecord',
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
            ],
            options={
                'verbose_name': 'Consent log',
                'verbose_name_plural': 'Consent logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('consent.consentevent',),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Consent record',
                'verbose_name_plural': 'Consent records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('consent.consentdecision',),
        ),
    ]
