# Generated by Django 5.2.8 on 2025-11-06 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_consentcategory_consentlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consentrecord',
            name='unique_consent_record',
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('user', 'policy_version', 'site_domain'), name='unique_consent_per_user'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.UniqueConstraint(fields=('session_key', 'policy_version', 'site_domain'), name='unique_consent_per_session'),
        ),
    ]
