# Generated by Django 5.2.8 on 2025-12-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_consentdecision_consentevent_remove_consentlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consentcategory',
            table='consent_consentcategory',
        ),
    ]
