# Generated by Django 5.2.8 on 2025-11-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0004_remove_consentrecord_unique_consent_record_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentrecord',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Consent record', 'verbose_name_plural': 'Consent records'},
        ),
    ]
