# Generated by Django 5.2.8 on 2025-11-08 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0005_alter_consentrecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentpolicy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consent policy', 'verbose_name_plural': 'Consent policies'},
        ),
        migrations.AlterField(
            model_name='consentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consentcategory',
            index=models.Index(fields=['slug'], name='consent_con_slug_27d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['timestamp'], name='consent_con_timesta_e77c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['policy_version'], name='consent_con_policy__19be15_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['site_domain'], name='consent_con_site_do_3c147b_idx'),
        ),
    ]
