# Generated by Django 5.2.8 on 2025-11-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0006_alter_consentpolicy_options_alter_consentlog_user_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentcategory',
            new_name='consent_cat_slug_idx',
            old_name='consent_con_slug_27d9ec_idx',
        ),
        migrations.RenameIndex(
            model_name='consentlog',
            new_name='consent_log_time_idx',
            old_name='consent_con_timesta_e77c0b_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_policy_idx',
            old_name='consent_con_policy__19be15_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_site_idx',
            old_name='consent_con_site_do_3c147b_idx',
        ),
    ]
