# Generated by Django 5.2.8 on 2025-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0007_rename_consent_con_slug_27d9ec_idx_consent_cat_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentpolicy',
            name='site_domain',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='consentpolicy',
            unique_together={('site_domain', 'version')},
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['site_domain'], name='consent_policy_site_idx'),
        ),
        migrations.AddIndex(
            model_name='consentpolicy',
            index=models.Index(fields=['version'], name='consent_policy_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='consentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site_domain', 'is_active'), name='unique_active_policy_per_site'),
        ),
    ]
