# Generated by Django 5.2.8 on 2025-11-08 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0008_consentpolicy_site_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), ('session_key__isnull', True), _negated=True), name='user_or_session_required'),
        ),
    ]
