# Generated by Django 5.2.8 on 2025-11-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0009_consentrecord_user_or_session_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consentpolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='policy_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consentlog',
            name='site_domain',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='policy',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional foreign key for audit traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='consent.consentpolicy', to_field='version'),
        ),
        migrations.AlterField(
            model_name='consentpolicy',
            name='version',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='policy_version',
            field=models.CharField(blank=True, db_column='policy_version_text', max_length=20),
        ),
    ]
