# Generated by Django 5.2.9 on 2025-12-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_initial_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['slug'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
