# Generated by Django 5.2.8 on 2025-11-18 21:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site', max_length=100)),
                ('site_header', models.CharField(default='Admin', max_length=100)),
                ('site_description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, help_text='Primary site logo (SVG/PNG)', null=True, upload_to='branding/')),
                ('dark_logo', models.ImageField(blank=True, help_text='Dark mode logo', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (PNG/ICO/SVG)', null=True, upload_to='branding/')),
                ('theme_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('enable_localization', models.BooleanField(default=False)),
                ('enable_ai_personalization', models.BooleanField(default=False)),
                ('ai_theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('ai_model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('enable_signup', models.BooleanField(default=True)),
                ('enable_password_reset', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('force_https', models.BooleanField(default=False, help_text='Enable only if TLS is enforced by reverse proxy')),
                ('recaptcha_enabled', models.BooleanField(default=False)),
                ('recaptcha_mode', models.CharField(choices=[('v2', 'v2'), ('v3', 'v3')], default='v2', max_length=20)),
                ('recaptcha_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('recaptcha_private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('recaptcha_score_threshold', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recaptcha_timeout_ms', models.PositiveIntegerField(default=3000)),
                ('max_devices_per_user', models.PositiveIntegerField(default=3)),
                ('lock_duration_minutes', models.PositiveIntegerField(default=15)),
                ('fingerprint_mode', models.CharField(choices=[('strict', 'Strict'), ('lenient', 'Lenient')], default='strict', max_length=20)),
                ('enforce_unique_device', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=False)),
                ('mfa_totp_issuer', models.CharField(default='Site', max_length=50)),
                ('email_verification_code_length', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('email_verification_code_type', models.CharField(choices=[('numeric', 'Numeric'), ('alphanumeric', 'Alphanumeric')], default='alphanumeric', max_length=20)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=300)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=600)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('file', models.FileField(upload_to='verification/')),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['provider'], name='ver_file_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsVerificationFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_file_links', to='site_settings.sitesettings')),
                ('verification_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='site_settings.verificationfile')),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='verification_files',
            field=models.ManyToManyField(blank=True, through='site_settings.SiteSettingsVerificationFileLink', to='site_settings.verificationfile'),
        ),
        migrations.CreateModel(
            name='VerificationMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('name_attr', models.CharField(max_length=100)),
                ('content_attr', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'name_attr'], name='ver_meta_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_profile', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='sites.site')),
                ('verification_files', models.ManyToManyField(blank=True, to='site_settings.verificationfile')),
                ('meta_tags', models.ManyToManyField(blank=True, to='site_settings.verificationmetatag')),
            ],
            options={
                'verbose_name': 'Tenant Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsMetaTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag_links', to='site_settings.sitesettings')),
                ('meta_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='site_settings.verificationmetatag')),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_tags',
            field=models.ManyToManyField(blank=True, through='site_settings.SiteSettingsMetaTagLink', to='site_settings.verificationmetatag'),
        ),
        migrations.AddIndex(
            model_name='sitesettingsverificationfilelink',
            index=models.Index(fields=['site_settings', 'verification_file'], name='site_file_link_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitesettingsverificationfilelink',
            unique_together={('site_settings', 'verification_file')},
        ),
        migrations.AddIndex(
            model_name='sitesettingsmetataglink',
            index=models.Index(fields=['site_settings', 'meta_tag'], name='site_meta_link_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitesettingsmetataglink',
            unique_together={('site_settings', 'meta_tag')},
        ),
    ]
