# Generated by Django 5.2.8 on 2025-11-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GsmInfinity', max_length=128)),
                ('site_header', models.CharField(default='Admin Panel', max_length=128)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('theme_profile', models.CharField(default='default', max_length=64)),
                ('primary_color', models.CharField(default='#0057B8', max_length=7)),
                ('secondary_color', models.CharField(default='#FFD700', max_length=7)),
                ('default_language', models.CharField(default='en-us', max_length=16)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64)),
                ('enable_localization', models.BooleanField(default=True)),
                ('enable_ai_personalization', models.BooleanField(default=True)),
                ('ai_theme_mode', models.CharField(choices=[('auto', 'Auto'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=16)),
                ('ai_model_version', models.CharField(default='v1.0', max_length=32)),
                ('enable_signup', models.BooleanField(default=True)),
                ('enable_password_reset', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('recaptcha_enabled', models.BooleanField(default=True)),
                ('recaptcha_public_key', models.CharField(blank=True, max_length=200)),
                ('recaptcha_private_key', models.CharField(blank=True, max_length=200)),
                ('recaptcha_mode', models.CharField(choices=[('v2', 'reCAPTCHA v2'), ('v3', 'reCAPTCHA v3'), ('off', 'Disabled')], default='v2', max_length=5)),
                ('recaptcha_score_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('recaptcha_timeout_ms', models.PositiveIntegerField(default=5000)),
                ('max_devices_per_user', models.IntegerField(default=3)),
                ('lock_duration_minutes', models.IntegerField(default=60)),
                ('fingerprint_mode', models.CharField(choices=[('all', 'Motherboard + OS'), ('mb', 'Motherboard Only'), ('os', 'OS Only'), ('none', 'No Fingerprint Lock')], default='all', max_length=10)),
                ('enforce_unique_device', models.BooleanField(default=False)),
                ('require_mfa', models.BooleanField(default=False)),
                ('mfa_totp_issuer', models.CharField(default='GsmInfinity', max_length=64)),
                ('email_verification_code_length', models.PositiveIntegerField(default=6)),
                ('email_verification_code_type', models.CharField(choices=[('numeric', 'Numeric'), ('alphanumeric', 'Alphanumeric')], default='alphanumeric', max_length=12)),
                ('max_login_attempts', models.PositiveIntegerField(default=10)),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=300)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='e.g. Google, LinkedIn, Bing', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Purpose / requester / ticket ref', null=True)),
                ('file', models.FileField(upload_to='verification/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_files', to='site_settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Verification file',
                'verbose_name_plural': 'Verification files',
            },
        ),
        migrations.CreateModel(
            name='VerificationMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='e.g. Google, Bing, Facebook, LinkedIn', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Reason/use, requester, ticket ref', null=True)),
                ('name_attr', models.CharField(help_text='meta name attribute (e.g. google-site-verification)', max_length=200)),
                ('content_attr', models.CharField(help_text='meta content value/code', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='site_settings.sitesettings')),
            ],
            options={
                'verbose_name': 'Verification meta tag',
                'verbose_name_plural': 'Verification meta tags',
            },
        ),
        migrations.CreateModel(
            name='TenantSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_profile', models.CharField(default='default', max_length=64)),
                ('primary_color', models.CharField(default='#0057B8', max_length=7)),
                ('secondary_color', models.CharField(default='#FFD700', max_length=7)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='sites.site')),
                ('verification_files', models.ManyToManyField(blank=True, to='site_settings.verificationfile')),
                ('meta_tags', models.ManyToManyField(blank=True, to='site_settings.verificationmetatag')),
            ],
        ),
        migrations.AddIndex(
            model_name='verificationfile',
            index=models.Index(fields=['provider'], name='site_settin_provide_2ecaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationmetatag',
            index=models.Index(fields=['provider', 'name_attr'], name='site_settin_provide_ff8ba8_idx'),
        ),
    ]
