# Generated by Django 5.2.8 on 2025-11-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='tenantsitesettings',
            options={'verbose_name': 'Tenant Site Settings', 'verbose_name_plural': 'Tenant Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='verificationfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Verification File', 'verbose_name_plural': 'Verification Files'},
        ),
        migrations.AlterModelOptions(
            name='verificationmetatag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Meta Tag', 'verbose_name_plural': 'Verification Meta Tags'},
        ),
        migrations.RemoveIndex(
            model_name='verificationfile',
            name='site_settin_provide_2ecaf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationmetatag',
            name='site_settin_provide_ff8ba8_idx',
        ),
        migrations.RemoveField(
            model_name='tenantsitesettings',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='verificationfile',
            name='site_settings',
        ),
        migrations.RemoveField(
            model_name='verificationmetatag',
            name='site_settings',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_tags',
            field=models.ManyToManyField(blank=True, to='site_settings.verificationmetatag'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='verification_files',
            field=models.ManyToManyField(blank=True, to='site_settings.verificationfile'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ai_model_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ai_theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cache_ttl_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_verification_code_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('alphanumeric', 'Alphanumeric')], default='alphanumeric', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_ai_personalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_localization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enforce_unique_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='fingerprint_mode',
            field=models.CharField(choices=[('strict', 'Strict'), ('lenient', 'Lenient')], default='strict', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lock_duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_devices_per_user',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mfa_totp_issuer',
            field=models.CharField(default='GsmInfinity', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_mode',
            field=models.CharField(choices=[('v2', 'v2'), ('v3', 'v3')], default='v2', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_score_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='recaptcha_timeout_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_header',
            field=models.CharField(default='GSM Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='GsmInfinity', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantsitesettings',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsitesettings',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsitesettings',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='tenantsitesettings',
            name='theme_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificationfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='verificationfile',
            name='provider',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationmetatag',
            name='content_attr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationmetatag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='verificationmetatag',
            name='name_attr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verificationmetatag',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
