# Generated by Django 5.2.8 on 2025-11-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_options_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_tags',
            field=models.ManyToManyField(blank=True, related_name='site_settings_meta', to='site_settings.verificationmetatag'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='verification_files',
            field=models.ManyToManyField(blank=True, related_name='site_settings_files', to='site_settings.verificationfile'),
        ),
        migrations.AlterField(
            model_name='tenantsitesettings',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='verificationfile',
            name='provider',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationmetatag',
            name='provider',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='verificationfile',
            index=models.Index(fields=['provider'], name='site_settin_provide_2ecaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationmetatag',
            index=models.Index(fields=['provider', 'name_attr'], name='site_settin_provide_ff8ba8_idx'),
        ),
    ]
