# Generated by Django 5.2.8 on 2025-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_enable_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ad_aggressiveness_level',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ad_networks_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ads_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='affiliate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_linking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_meta_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_schema_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
