# Generated by Django 5.2.8 on 2025-12-04 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_allow_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='ad_aggressiveness_level',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ad_networks_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ads_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='affiliate_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ai_model_version',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ai_theme_mode',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='allow_user_blog_posts',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='allow_user_bounty_posts',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_linking_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_meta_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_schema_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_ai_personalization',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_blog',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_blog_comments',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_notifications',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_password_reset',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_signup',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_tenants',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='theme_profile',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Deprecated: colors now come from the Themes app; kept for legacy templates.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Deprecated: colors now come from the Themes app; kept for legacy templates.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #0d6efd', regex='^#(?:[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.DeleteModel(
            name='TenantSiteSettings',
        ),
    ]
