# Generated by Django 5.0.6 on 2025-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_gmail_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_profile_completion',
            field=models.BooleanField(default=True, help_text='Require social auth users to complete profile before accessing the site'),
        ),
    ]
