# Generated by Django 5.2.9 on 2025-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_add_require_profile_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='winternotes_enabled',
            field=models.BooleanField(default=True, help_text='Enable WinterNotes rich text editor for blog posts and admin.'),
        ),
    ]
