# Generated by Django 5.2.9 on 2025-12-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_sitesettings_winternotes_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='winternotes_enabled',
        ),
    ]
