# Generated by Django 5.2.9 on 2025-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_remove_sitesettings_winternotes_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_languages',
            field=models.CharField(blank=True, default='en,ar,fr,de,es,zh-hans,ja,ko,ru,pt', help_text='Comma-separated language codes to show in header (max 10). Other languages remain available via full selector.', max_length=200),
        ),
    ]
