# Generated by Django 5.2.9 on 2025-12-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0999_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='firmwarestoragelocation',
            name='firmware_storage_ct_idx',
        ),
        migrations.RemoveIndex(
            model_name='firmwarestoragelocation',
            name='firmware_storage_drive_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceaccount',
            name='service_account_drive_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceaccount',
            name='service_account_quota_idx',
        ),
        migrations.RemoveIndex(
            model_name='shareddriveaccount',
            name='shared_drive_usage_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdownloadsession',
            name='download_session_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdownloadsession',
            name='download_session_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='userdownloadsession',
            name='download_session_sa_idx',
        ),
    ]
