# Generated by Django 5.2.9 on 2025-12-23 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0999_enhance_firmware_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='model',
            name='model_brand_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingfirmware',
            name='pending_fw_uploader_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingfirmware',
            name='pending_fw_brand_model_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='variant_model_name_idx',
        ),
        migrations.RenameIndex(
            model_name='engineeringfirmware',
            new_name='eng_hierarchy_idx',
            old_name='eng_fw_hierarchy_idx',
        ),
        migrations.RenameIndex(
            model_name='modifiedfirmware',
            new_name='mod_hierarchy_idx',
            old_name='mod_fw_hierarchy_idx',
        ),
        migrations.RenameIndex(
            model_name='officialfirmware',
            new_name='off_hierarchy_idx',
            old_name='official_fw_hierarchy_idx',
        ),
        migrations.RenameIndex(
            model_name='officialfirmware',
            new_name='off_created_idx',
            old_name='official_fw_created_idx',
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='android_version',
            field=models.CharField(blank=True, default='', help_text='Android version (e.g., 14.0)', max_length=32),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='build_date',
            field=models.DateField(blank=True, help_text='Build date', null=True),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='build_number',
            field=models.CharField(blank=True, default='', help_text='Build number/version', max_length=128),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total downloads'),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash', max_length=256),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for download'),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='security_patch',
            field=models.DateField(blank=True, help_text='Security patch date', null=True),
        ),
        migrations.AddField(
            model_name='engineeringfirmware',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total views'),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='android_version',
            field=models.CharField(blank=True, default='', help_text='Android version (e.g., 14.0)', max_length=32),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='build_date',
            field=models.DateField(blank=True, help_text='Build date', null=True),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='build_number',
            field=models.CharField(blank=True, default='', help_text='Build number/version', max_length=128),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total downloads'),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash', max_length=256),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for download'),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='security_patch',
            field=models.DateField(blank=True, help_text='Security patch date', null=True),
        ),
        migrations.AddField(
            model_name='modifiedfirmware',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total views'),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='android_version',
            field=models.CharField(blank=True, default='', help_text='Android version (e.g., 14.0)', max_length=32),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='build_date',
            field=models.DateField(blank=True, help_text='Build date', null=True),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='build_number',
            field=models.CharField(blank=True, default='', help_text='Build number/version', max_length=128),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total downloads'),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash', max_length=256),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for download'),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='security_patch',
            field=models.DateField(blank=True, help_text='Security patch date', null=True),
        ),
        migrations.AddField(
            model_name='otherfirmware',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total views'),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='android_version',
            field=models.CharField(blank=True, default='', help_text='Android version (e.g., 14.0)', max_length=32),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='build_date',
            field=models.DateField(blank=True, help_text='Build date', null=True),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='build_number',
            field=models.CharField(blank=True, default='', help_text='Build number/version', max_length=128),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total downloads'),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash', max_length=256),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for download'),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='security_patch',
            field=models.DateField(blank=True, help_text='Security patch date', null=True),
        ),
        migrations.AddField(
            model_name='readbackfirmware',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total views'),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='android_version',
            field=models.CharField(blank=True, default='', help_text='Android version (e.g., 14.0)', max_length=32),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='build_date',
            field=models.DateField(blank=True, help_text='Build date', null=True),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='build_number',
            field=models.CharField(blank=True, default='', help_text='Build number/version', max_length=128),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Total downloads'),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash', max_length=256),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for download'),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='security_patch',
            field=models.DateField(blank=True, help_text='Security patch date', null=True),
        ),
        migrations.AddField(
            model_name='unclassifiedfirmware',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total views'),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='Device model name (e.g., Galaxy S23)', max_length=128),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Chipset/Processor', max_length=128),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='original_file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='partitions',
            field=models.JSONField(blank=True, default=list, help_text='Partition list'),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='stored_file_path',
            field=models.CharField(help_text='Storage path in system', max_length=500),
        ),
        migrations.AlterField(
            model_name='variant',
            name='board_id',
            field=models.CharField(blank=True, default='', help_text='Board ID for hardware identification', max_length=128),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(help_text='Variant name (e.g., Global, US, EU)', max_length=128),
        ),
        migrations.AlterField(
            model_name='variant',
            name='region',
            field=models.CharField(blank=True, default='', help_text='Region code (e.g., SM, EU, US, CN)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='engineeringfirmware',
            index=models.Index(fields=['chipset'], name='eng_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringfirmware',
            index=models.Index(fields=['android_version'], name='eng_android_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='eng_status_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringfirmware',
            index=models.Index(fields=['-created_at'], name='eng_created_idx'),
        ),
        migrations.AddIndex(
            model_name='modifiedfirmware',
            index=models.Index(fields=['chipset'], name='mod_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='modifiedfirmware',
            index=models.Index(fields=['android_version'], name='mod_android_idx'),
        ),
        migrations.AddIndex(
            model_name='modifiedfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='mod_status_idx'),
        ),
        migrations.AddIndex(
            model_name='modifiedfirmware',
            index=models.Index(fields=['-created_at'], name='mod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='officialfirmware',
            index=models.Index(fields=['chipset'], name='off_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='officialfirmware',
            index=models.Index(fields=['android_version'], name='off_android_idx'),
        ),
        migrations.AddIndex(
            model_name='officialfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='off_status_idx'),
        ),
        migrations.AddIndex(
            model_name='otherfirmware',
            index=models.Index(fields=['brand', 'model', 'variant'], name='oth_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='otherfirmware',
            index=models.Index(fields=['chipset'], name='oth_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='otherfirmware',
            index=models.Index(fields=['android_version'], name='oth_android_idx'),
        ),
        migrations.AddIndex(
            model_name='otherfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='oth_status_idx'),
        ),
        migrations.AddIndex(
            model_name='otherfirmware',
            index=models.Index(fields=['-created_at'], name='oth_created_idx'),
        ),
        migrations.AddIndex(
            model_name='readbackfirmware',
            index=models.Index(fields=['brand', 'model', 'variant'], name='rb_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='readbackfirmware',
            index=models.Index(fields=['chipset'], name='rb_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='readbackfirmware',
            index=models.Index(fields=['android_version'], name='rb_android_idx'),
        ),
        migrations.AddIndex(
            model_name='readbackfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='rb_status_idx'),
        ),
        migrations.AddIndex(
            model_name='readbackfirmware',
            index=models.Index(fields=['-created_at'], name='rb_created_idx'),
        ),
        migrations.AddIndex(
            model_name='unclassifiedfirmware',
            index=models.Index(fields=['brand', 'model', 'variant'], name='unc_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='unclassifiedfirmware',
            index=models.Index(fields=['chipset'], name='unc_chipset_idx'),
        ),
        migrations.AddIndex(
            model_name='unclassifiedfirmware',
            index=models.Index(fields=['android_version'], name='unc_android_idx'),
        ),
        migrations.AddIndex(
            model_name='unclassifiedfirmware',
            index=models.Index(fields=['is_verified', 'is_active'], name='unc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unclassifiedfirmware',
            index=models.Index(fields=['-created_at'], name='unc_created_idx'),
        ),
    ]
