"""
Enhanced Tag models with enterprise-grade features.
Includes trending, analytics, relationships, and AI-powered features.
"""
from __future__ import annotations

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from apps.core.models import TimestampedModel, SoftDeleteModel


class TagCategory(TimestampedModel, SoftDeleteModel):
    """
    Group tags into categories for better organization.
    Examples: Programming Languages, Frameworks, Topics, Industries
    """
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=120, unique=True)
    description = models.TextField(blank=True, default="")
    color = models.CharField(max_length=7, default="#3B82F6", help_text="Hex color code")
    icon = models.CharField(max_length=50, blank=True, default="", help_text="Icon class or emoji")
    display_order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["display_order", "name"]
        verbose_name_plural = "Tag Categories"
    
    def __str__(self) -> str:
        return self.name


class TagRelationship(TimestampedModel):
    """
    Define relationships between tags (synonyms, related, broader/narrower).
    Enables intelligent tag suggestions and navigation.
    """
    class RelationType(models.TextChoices):
        SYNONYM = "synonym", "Synonym"
        RELATED = "related", "Related"
        BROADER = "broader", "Broader Topic"
        NARROWER = "narrower", "Narrower Topic"
        REPLACES = "replaces", "Replaces"
        EQUIVALENT = "equivalent", "Equivalent"
    
    from_tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="relationships_from"
    )
    to_tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="relationships_to"
    )
    relationship_type = models.CharField(max_length=20, choices=RelationType.choices)
    strength = models.FloatField(
        default=1.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],
        help_text="Relationship strength (0.0-1.0)"
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    auto_generated = models.BooleanField(default=False, help_text="Generated by AI/algorithm")
    
    class Meta:
        unique_together = [["from_tag", "to_tag", "relationship_type"]]
        indexes = [
            models.Index(fields=["from_tag", "relationship_type"]),
            models.Index(fields=["to_tag", "relationship_type"]),
        ]
    
    def __str__(self) -> str:
        return f"{self.from_tag} → {self.get_relationship_type_display()} → {self.to_tag}"


class TagTrending(models.Model):
    """
    Track trending tags over different time periods.
    Updated by periodic tasks.
    """
    class Period(models.TextChoices):
        HOURLY = "hourly", "Last Hour"
        DAILY = "daily", "Last 24 Hours"
        WEEKLY = "weekly", "Last 7 Days"
        MONTHLY = "monthly", "Last 30 Days"
    
    tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="trending_data"
    )
    period = models.CharField(max_length=20, choices=Period.choices)
    usage_count = models.PositiveIntegerField(default=0)
    growth_rate = models.FloatField(default=0.0, help_text="Percentage growth vs previous period")
    trending_score = models.FloatField(default=0.0, help_text="Composite trending score")
    rank = models.PositiveIntegerField(default=0)
    calculated_at = models.DateTimeField(default=timezone.now)
    
    class Meta:
        unique_together = [["tag", "period"]]
        ordering = ["period", "rank"]
        indexes = [
            models.Index(fields=["period", "rank"]),
            models.Index(fields=["period", "-trending_score"]),
        ]
    
    def __str__(self) -> str:
        return f"{self.tag} trending {self.period}: rank #{self.rank}"


class TagAnalytics(models.Model):
    """
    Comprehensive analytics for tags.
    """
    tag = models.OneToOneField(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="analytics",
        primary_key=True
    )
    total_usage = models.PositiveIntegerField(default=0)
    unique_authors = models.PositiveIntegerField(default=0)
    avg_engagement = models.FloatField(default=0.0, help_text="Average engagement of tagged content")
    first_used = models.DateTimeField(null=True, blank=True)
    last_used = models.DateTimeField(null=True, blank=True)
    peak_usage_date = models.DateField(null=True, blank=True)
    peak_usage_count = models.PositiveIntegerField(default=0)
    growth_rate_7d = models.FloatField(default=0.0)
    growth_rate_30d = models.FloatField(default=0.0)
    quality_score = models.FloatField(default=0.0, help_text="Content quality score for this tag")
    last_calculated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = "Tag Analytics"
        indexes = [
            models.Index(fields=["-total_usage"]),
            models.Index(fields=["-avg_engagement"]),
            models.Index(fields=["-quality_score"]),
        ]
    
    def __str__(self) -> str:
        return f"Analytics for {self.tag}: {self.total_usage} uses"


class TagSubscription(TimestampedModel):
    """
    Allow users to follow/subscribe to tags for notifications.
    """
    tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="subscriptions"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="tag_subscriptions"
    )
    notification_frequency = models.CharField(
        max_length=20,
        choices=[
            ("instant", "Instant"),
            ("daily", "Daily Digest"),
            ("weekly", "Weekly Digest"),
            ("never", "Never (Bookmark Only)")
        ],
        default="instant"
    )
    is_active = models.BooleanField(default=True)
    
    class Meta:
        unique_together = [["tag", "user"]]
        indexes = [
            models.Index(fields=["user", "is_active"]),
            models.Index(fields=["tag", "notification_frequency"]),
        ]
    
    def __str__(self) -> str:
        return f"{self.user} subscribed to {self.tag}"


class TagSuggestion(TimestampedModel):
    """
    User-submitted or AI-generated tag suggestions.
    Requires curation before activation.
    """
    class Status(models.TextChoices):
        PENDING = "pending", "Pending Review"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"
        MERGED = "merged", "Merged with Existing"
    
    suggested_name = models.CharField(max_length=64)
    normalized_name = models.CharField(max_length=64)
    description = models.TextField(blank=True, default="")
    suggested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="tag_suggestions"
    )
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    ai_generated = models.BooleanField(default=False)
    ai_confidence = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)]
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reviewed_tag_suggestions"
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    created_tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_from_suggestion"
    )
    rejection_reason = models.TextField(blank=True, default="")
    
    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "-created_at"]),
            models.Index(fields=["suggested_by", "status"]),
        ]
    
    def __str__(self) -> str:
        return f"Suggestion: '{self.suggested_name}' by {self.suggested_by} ({self.status})"


class TagBlacklist(TimestampedModel):
    """
    Blacklist inappropriate or problematic tag names.
    """
    pattern = models.CharField(max_length=100, unique=True, help_text="Exact match or regex pattern")
    is_regex = models.BooleanField(default=False)
    reason = models.TextField(blank=True, default="")
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    is_active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["pattern"]
    
    def __str__(self) -> str:
        return f"Blacklist: {self.pattern}"


class TagMerge(TimestampedModel):
    """
    Track tag merges for historical record.
    """
    source_tag_name = models.CharField(max_length=64)
    target_tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="merge_history"
    )
    merged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    reason = models.TextField(blank=True, default="")
    items_migrated = models.PositiveIntegerField(default=0)
    
    class Meta:
        ordering = ["-created_at"]
    
    def __str__(self) -> str:
        return f"Merged '{self.source_tag_name}' into {self.target_tag}"


class TagCollection(TimestampedModel):
    """
    User-created collections of related tags.
    Similar to playlists for music.
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120)
    description = models.TextField(blank=True, default="")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="tag_collections"
    )
    tags = models.ManyToManyField(
        "tags.Tag",
        related_name="in_collections",
        through="TagCollectionItem"
    )
    is_public = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    follower_count = models.PositiveIntegerField(default=0)
    
    class Meta:
        unique_together = [["owner", "slug"]]
        ordering = ["-created_at"]
    
    def __str__(self) -> str:
        return f"{self.name} by {self.owner}"


class TagCollectionItem(TimestampedModel):
    """
    Individual items in tag collections with ordering.
    """
    collection = models.ForeignKey(
        TagCollection,
        on_delete=models.CASCADE,
        related_name="items"
    )
    tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE
    )
    order = models.PositiveIntegerField(default=0)
    notes = models.TextField(blank=True, default="")
    
    class Meta:
        unique_together = [["collection", "tag"]]
        ordering = ["order", "id"]
    
    def __str__(self) -> str:
        return f"{self.tag} in {self.collection}"


class TagAlias(TimestampedModel):
    """
    Alternative names/spellings for tags (e.g., JS → JavaScript).
    Automatic redirect to canonical tag.
    """
    alias = models.CharField(max_length=64, unique=True)
    canonical_tag = models.ForeignKey(
        "tags.Tag",
        on_delete=models.CASCADE,
        related_name="aliases"
    )
    redirect_count = models.PositiveIntegerField(default=0)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    
    class Meta:
        verbose_name_plural = "Tag Aliases"
        ordering = ["alias"]
    
    def __str__(self) -> str:
        return f"{self.alias} → {self.canonical_tag}"
